create table if not exists public.reminder_dispatch_log (
    id bigint generated by default as identity primary key,
    user_id integer not null references public.user_profiles(id) on delete cascade,
    task_id integer not null references public.tasks(id) on delete cascade,
    reminder_date date not null,
    reminder_window_days integer not null,
    recipient_email text not null,
    provider text not null default 'brevo',
    delivery_status text not null default 'sent',
    error_message text,
    created_at timestamptz not null default timezone('utc', now()),
    unique (user_id, task_id, reminder_date, reminder_window_days)
);

create index if not exists idx_reminder_dispatch_log_lookup
    on public.reminder_dispatch_log (reminder_date, reminder_window_days, delivery_status);

drop function if exists public.get_pending_reminder_tasks(integer, date);

create or replace function public.get_pending_reminder_tasks(
    p_reminder_window_days integer default 5,
    p_run_date date default current_date
)
returns table (
    user_id integer,
    user_name text,
    user_email text,
    task_id integer,
    title text,
    deadline timestamp,
    priority integer,
    status text
)
language sql
security definer
set search_path = public
as $$
    select
        up.id as user_id,
        up.name::text as user_name,
        up.email::text as user_email,
        t.id as task_id,
        t.title::text as title,
        t.deadline as deadline,
        t.priority,
        t.status::text as status
    from public.user_profiles up
    join public.tasks t
        on t.user_id = up.id
    left join public.reminder_dispatch_log rdl
        on rdl.user_id = up.id
        and rdl.task_id = t.id
        and rdl.reminder_date = p_run_date
        and rdl.reminder_window_days = p_reminder_window_days
        and rdl.delivery_status = 'sent'
    where t.deadline is not null
      and t.deadline < (p_run_date + (p_reminder_window_days + 1))::timestamp
      and lower(coalesce(t.status, 'pending')) not in ('done', 'completed')
      and coalesce(t.deleted, false) = false
      and coalesce(trim(up.email), '') <> ''
      and rdl.id is null
    order by up.id, t.deadline asc, t.priority asc nulls last, t.id asc;
$$;
